version: '3'
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:0.9.2
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /opt/services/certs:/etc/nginx/certs
      - /opt/services/conf/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - services_net

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.471-jdk17
    volumes:
      - /opt/services/jenkins_lts:/var/jenkins_home
    restart: unless-stopped
    environment:
      - "VIRTUAL_HOST=domain_name"
      - "VIRTUAL_PORT=8080"
      - "TZ=Asia/Dubai"
    networks:
      - services_net
    user: "${UID}:${GID}"

networks:
   services_net:
     driver: bridge
